### PR TITLE
update for building with modern toolchain

### PR DESCRIPTION
**Pull request by matthargett**
Update autotools files, cherry pick compile fixes from upstream. Verified to build with GCC 4.9 on Ubuntu 15.x and gentoo, both on x86. GCC 5.2 also basically works, but requires -std=c++03 to be added to most of the builds: GCC 5.x defaults to C++11 and there is more code cleanup to do to make that work for compiles and to fix runtime crashes.

The next step is to test with @niluje x-compile.sh toolchain and see if we can start to replace the system-installed versions of the leaf node binaries with GCC 5.2-compiled versions using LTO -Os -fipa-pta -fdevirtualize-specualtively, etc. (See my tweets for stats on binary/memory size and performance improvements in WebKit/JavaScriptCore/etc using those optimizations.)

### CODE REVIEW

**Comment by tjwei** [comment]
thanks

**Comment by matthargett** [comment]
can you test these changes with your Kindle DX to make sure everything still works? if you can do it with a GCC 4.9 toolchain (instead of the 10 year old one), that would be even better.

I'd do this manual system testing myself, but I couldn't quite get the shell scripts in the github to work. I built everything by hand ;)

thanks!!

**Comment by tjwei** [comment]
I will try to build them this week.

**Comment by tjwei** [comment]
The test is delayed a bit because of Chinese new year.

**Comment by matthargett** [comment]
hope you had a good New Year celebration! can you test recompiling and testing in your environment?

**Comment by houqp** [comment]
Shameless plug, we have setup a repo based on @niluje's x-compile script to make it easier to maintain and share xtc infrastructure among the community: https://github.com/koreader/koxtoolchain. If you guys want to help maintain the repo, feel free to ping me so I can add you to the owner ;)

**Comment by matthargett** [comment]
@houqp that's awesome! I've done a lot of work and experiments with @niluje 's private x-tc repo, with great success. recompiling webkit with GCC 5.1 -Os -flto is a  revelation in performance and frees up hundreds of kilobytes of RAM, even with more webkit features enabled. I have also done benchmarking with versions of v8 and JavaScriptCore, which was the next step to advance the web browser on legacy Kindles with keyboards. v8 was the best bang for the buck -- Octane and other benchmarks were faster than on my PS4's browser! Go ahead and add me to that repo and I'll send some pull requests if I get time. THanks for making it easier to collaborate on the toolchain!

**Comment by NiLuJe** [comment]
FWIW, I'll move the ct-ng patches to a proper branch to ease maintenance soon, so it may be a good time to revisit actually trying to properly match the target glibc of legacy Kindles (i.e., 2.5, and not 2.9 like I'm currently doing), which would shave off a number of crappy & ugly workarounds...

**Comment by NiLuJe** [comment]
And, yeah, I maintain my stuff [over here](http://trac.ak-team.com/trac/browser/niluje/Configs/trunk/Kindle/Misc/x-compile.sh) ;).

**Comment by tjwei** [comment]
@houqp  @NiLuJe  Awesome works. Nice to see that.
@matthargett  Thanks, I am setting up the environment right now, trying to figure out how to use  koxtoolchain.

**Comment by houqp** [comment]
@matthargett added :) The performance gain from GCC 5.1 looks promising. It's probably worth the effort to maintain two profiles for each device, one that matches the stock legacy userspace and one for bleeding edge experimental build. 

@NiLuJe are you planning to move the config to github/bitbucket/gitlab anytime soon? If so, we should focus effort on your repo instead ;)

**Comment by NiLuJe** [comment]
Not necessarily, but then the config itself is fairly static, most of the
tweaks are done in CT-NG, mostly to deal with old kernels and glibc.

**Comment by NiLuJe** [comment]
Finished the move to git -> https://github.com/NiLuJe/crosstool-ng :).

I'll possibly use ct-ng's "sample" feature for bare-bones settings, but the full configs probably won't move ;).

**Comment by NiLuJe** [comment]
Okay, tried again to play with glibc 2.5.1... We're hitting weird circular dependencies with headers (the libc headers installation is looking for gcc headers, but we're only installing gcc headers after having installed the libc's...).

So, yeah, probably won't spend much more time on that particular experiment, but if anyone feels like hitting his head against a wall for a while, be my guest ;).

**Comment by NiLuJe** [comment]
Okay, things should now be in order.

I got (somewhat) to the bottom of my GCC 5.3 issues (building the TC against glibc < 2.19 basically creates something that silently generates bad code, for some reason I can't fathom).
I resolved my KOReader & CRe issue (I had some stray -I/-L flags in my environment that pulled stuff from my custom sysroot, which probably ended up causing an API or ABI mismatch).

And I just added samples for my four usual targets to the ct-ng branch, with relevant comments.

**Comment by NiLuJe** [comment]
I don't intend to tweak anything much for a while, so, whatever you want to do, @houqp, things should be calm now ^^.

**Comment by houqp** [comment]
Awesome! I will port it to the build script. Hopefully, we can eventually use this profile for our automated builds.

**Pull request merged**
